version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
      POSTGRES_DB: claide_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data\
    ports:
      - "5432:5432"
  api:
    image: caetanobca/claide:v1.1
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env
      - ./.env:/app/.env.prod