version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
      POSTGRES_DB: claide_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data\
    ports:
      - "5432:5432"
    networks:
      - claide-net
  api:
    image: caetanobca/claide:v1.2
    depends_on:
      - db
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=
      - PORT=
      - JWT_SECRET=
      - JWT_EXPIRATION=
      - LDAP_URL= 
      - LDAP_SEARCHBASE=
      - LDAP_GROUP=
      - CERT_PATH=
      - KEY_PATH=
      - TLS_ENABLE=
    volumes:
      - ./certs:/app/certs
    networks:
      - claide-net
networks:
  claide-net:
    driver: bridge
